Perfume:
  - prfm
  - perfume_um
  - ptatv
  - mirainomuseum
  - LEVEL3
AKB48:
  - akb48
  - akb
  - AKBvote2012
  - akbsenkyo
  - gcp29th
SKE48:
  - ske48
  - ske
東京女子流:
  - TGSJP
  - TGSlive
ぱすぽ☆:
  - passpo
スマイレージ:
  - smileage
Berryz工房:
  - berryz
℃-ute:
  - c_ute
モーニング娘。:
  - morningmusume
Not yet:
  - notyet
KARA:
  - kara
ノースリーブス:
  - no3b
SDN48:
  - sdn48
  - sdn
NMB48:
  - nmb48
  - nmb
ももいろクローバーZ:
  - momoclo
  - momocloz
  - momoclo24
  - 五次元
Buono!:
  - buono
真野恵里菜:
  - manoerina
YGA:
  - YGA
Tomato n’ Pine:
  - Tomapai
SUPER☆GiRLS:
  - SUPER_GiRLS
バニラビーンズ:
  - vanibe
  - vanillabeans
HKT48:
  - hkt48
  - hkt
私立恵比寿中学:
  - ebichu
9nine:
  - 9nine
アイドリング!!!:
  - idoling
渡り廊下走り隊:
  - watarirouka
少女時代:
  - snsd
SCANDAL:
  - scndl
中川翔子:
  - shoko
乃木坂46:
  - nogizaka46
  - 乃木坂46
Aira Mitsuki:
  - airamitsuki
Saori@destiny:
  - saorid
Negicco:
  - Negicco
  - Negicco10th
JKT48:
  - jkt48
Dorothy Little Happy:
  - dorothylh
Fairies:
  - morekiss
party rocket:
  - パティロケ
しず風＆絆〜KIZUNA〜:
  - 絆834
  - しず風
いずこねこ:
  - izuko_tv
  - sakurai_tv
BiS:
 - BiS
 - BiS_idol
でんぱ組.inc:
 - dempagumi
アップアップガールズ（仮）:
 - uugirl
 - アプガ
lyrical school:
 - lyricalschool
 - リリスク
LinQ:
 - LinQ
さくら学院:
 - さくら学院
BABYMETAL:
 - babymetal
Prizmmy☆:
 - prizmmy
小桃音まい:
 - まいにゃ
EBiDAN:
 - EBiDAN
とちおとめ25:
 - とちおとめ25
たこやきレインボー:
 - たこ虹
チームしゃちほこ:
 - syachi
Especia:
 - Especia
 - EspeciaGG
RYUTist:
 - RYUTist
つりビット:
 - tsuri_bit

